# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create_date')),
                ('create_user', models.CharField(default='anoymous', max_length=100, verbose_name='create_user')),
                ('hair_type', models.IntegerField(choices=[(1, 'straight'), (2, 'wavy'), (3, 'curly'), (4, 'coily')], verbose_name='hair_type')),
                ('hair_structure', models.IntegerField(choices=[(1, 'fine'), (2, 'medium'), (3, 'coarse')], verbose_name='hair_structure')),
                ('scalp_moisture', models.IntegerField(choices=[(1, 'dry'), (2, 'normal'), (3, 'oily')], verbose_name='scale_moisture')),
                ('goals', models.CharField(max_length=200, null=True, verbose_name='goals')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
