# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='create_date')),
                ('create_user', models.CharField(default='anoymous', max_length=100, verbose_name='create_user')),
                ('hair_type', models.IntegerField(choices=[(1, 'straight'), (2, 'wavy'), (3, 'curly'), (4, 'coily')], null=True, verbose_name='hair_type')),
                ('hair_structure', models.IntegerField(choices=[(1, 'fine'), (2, 'medium'), (3, 'coarse')], null=True, verbose_name='hair_structure')),
                ('scalp_moisture', models.IntegerField(choices=[(1, 'dry'), (2, 'normal'), (3, 'oily')], null=True, verbose_name='scale_moisture')),
                ('goals', models.CharField(max_length=200, null=True, verbose_name='goals')),
                ('shampoo_color', models.IntegerField(choices=[(1, 'blue'), (2, 'pink'), (3, 'purple')], null=True, verbose_name='shampoo_color')),
                ('conditioner_color', models.IntegerField(choices=[(1, 'blue'), (2, 'pink'), (3, 'purple')], null=True, verbose_name='conditioner_color')),
                ('fragrance', models.IntegerField(choices=[(1, 'all(you)'), (2, 'calyptus'), (3, 'hibis(kiss)'), (4, 'musk - have'), (5, 'peony'), (6, 'tail'), (7, 'feeling(f)'), (8, 'ineapple')], null=True, verbose_name='fragrance')),
                ('fragrance_strength', models.IntegerField(choices=[(1, 'Light'), (2, 'Medium'), (3, 'Strong')], null=True, verbose_name='frangrance_strength')),
                ('shampoo_size', models.IntegerField(choices=[(0, ''), (1, '500ml'), (7, '1000ml')], null=True, verbose_name='shampoo_size')),
                ('conditioner_size', models.IntegerField(choices=[(0, ''), (1, '500ml'), (7, '1000ml')], null=True, verbose_name='conditioner_size')),
                ('formula_name', models.CharField(max_length=200, null=True, verbose_name='formula_name')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
