# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hair_structure',
            field=models.CharField(default='1', max_length=20, verbose_name=''),
        ),
        migrations.AddField(
            model_name='order',
            name='hair_type',
            field=models.CharField(default='1', max_length=20, verbose_name=''),
        ),
        migrations.AddField(
            model_name='order',
            name='scalp_moisture',
            field=models.CharField(default='1', max_length=20, verbose_name=''),
        ),
    ]
